[package]
name = "sqlo2_wasm_repl"
version = "0.1.0"
edition = "2018"

[dependencies]
sqlo2 = { path = "../engine", features = ["stdweb", "wasm-bindgen"] }

yew = "0.18"
yew-router = "0.15"
lazy_static = "1"
serde = "1"
serde_qs = "0.8"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-logger = "0.2"
log = "0.4"

[profile.release]
opt-level = "s"