[workspace]

members = [
    "engine",
    "benchmarks",
    "repl",
    "server",
    "test-util",
    "test-test",
    "wasm-repl",
    "wire-protocol"
]

[profile.bench]
debug = true
lto = "thin"

[profile.test]
debug = true

[profile.release]
debug = false
lto = "thin"
