[workspace]

members = [
    "engine",
    "benchmarks",
    "repl",
    "server",
    "test_util",
    "test_test",
    "wasm_client",
    "wasm_repl",
    "wire_protocol"
]

[profile.bench]
debug = true