[workspace]

members = [
    "engine",
    "benchmarks",
    "repl",
    "server",
    "test-util",
    "test-test",
    "wasm-client",
    "wasm-repl",
    "wire-protocol"
]

[profile.bench]
debug = true