
CREATE TABLE characters (id INT PRIMARY KEY, name TEXT);
INSERT INTO characters VALUES (0, 'Phantaminum');
INSERT INTO characters VALUES (1, 'The 25th Bam');
INSERT INTO characters VALUES (2, 'Rachel');
INSERT INTO characters VALUES (3, 'Rak WraithKaiser');
INSERT INTO characters VALUES (4, 'Khun Aguero Agnes');
INSERT INTO characters VALUES (5, 'King Zahard');
INSERT INTO characters VALUES (6, 'Ha Yuri Zahard');
INSERT INTO characters VALUES (7, 'Androssi Zahard');
INSERT INTO characters VALUES (8, 'Evankhell');
INSERT INTO characters VALUES (9, 'Anak Zahard');
INSERT INTO characters VALUES (10, 'Yeon Yihwa');
INSERT INTO characters VALUES (11, 'Yeo Miseng');
INSERT INTO characters VALUES (12, 'Yeo Goseng');
INSERT INTO characters VALUES (13, 'Xia Xia');
INSERT INTO characters VALUES (14, 'Sachi Faker');
INSERT INTO characters VALUES (15, 'Hwa Ryun');
INSERT INTO characters VALUES (16, 'Khun Ran');
INSERT INTO characters VALUES (17, 'Ha Yura');
SELECT id, name FROM characters;
SELECT id, name FROM characters WHERE id != 2;
SELECT id, name FROM characters WHERE name = 'Rachel';
SELECT id, name as charName FROM characters WHERE name != 'Rachel' AND id < 5;
SELECT name FROM characters ORDER BY name ASC;
SELECT DISTINCT (id / 2)::int FROM characters;
SELECT id::text || ' ' || name AS name_with_id FROM characters WHERE id > 1 ORDER BY id DESC LIMIT 4 OFFSET 5;
CREATE TABLE character_roles (character_id INT, role_name TEXT);
INSERT INTO character_roles VALUES (1, 'Wave Controller');
INSERT INTO character_roles VALUES (2, 'Light Bearer');
INSERT INTO character_roles VALUES (3, 'Spear Bearer');
INSERT INTO character_roles VALUES (4, 'Light Bearer');
INSERT INTO character_roles VALUES (1, 'Fisherman');
INSERT INTO character_roles VALUES (4, 'Spear Bearer');