[package]
name = "sqlo2_server"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlo2_wire-protocol = { path = "../wire-protocol" }
sqlo2 = { path = "../engine" }
byteorder = "=1.4.3"
log = "=0.4.17"
env_logger = "=0.9.0"
dotenv = "=0.15.0"