[package]
name = "sqlo2_repl"
version = "0.1.0"
authors = ["Axmouth <aggronfg@yahoo.com>"]
edition = "2018"

[dependencies]
sqlo2 = { path = "../engine" }
prettytable-rs = "^0.8"
rustc_version_runtime = "0.2"
rustyline = "9.0"
sysinfo = "0.20"