[package]
name = "sqlo2_repl"
version = "0.1.0"
authors = ["Axmouth <aggronfg@yahoo.com>"]
edition = "2021"

[dependencies]
sqlo2 = { path = "../engine" }
prettytable-rs = "=0.8.0"
rustc_version_runtime = "=0.2"
rustyline = "=9.1.2"
sysinfo = "=0.23.0"